version: '3'

services:
  recordstore-db:
    build: db
    image: grnc-recordstore-db
    ports:
      - "3306:3306"
    #environment:
      #- MYSQL_ROOT_PASSWORD=grncDocker
      #- MYSQL_ROOT_HOST=%